name: Sync Docs to Mintlify

on:
  push:
    branches: [main]
    paths:
      - "templates/**/cookbook.md"

jobs:
  sync-docs:
    name: Sync Cookbooks to Helicone Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout helicone-templates
        uses: actions/checkout@v3
        with:
          path: helicone-templates

      - name: Get changed files
        id: changed_files
        run: |
          echo "CHANGED_FILES=$(cd helicone-templates && git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'cookbook.md' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Checkout helicone-docs repo
        uses: actions/checkout@v3
        with:
          repository: helicone/helicone-docs
          path: helicone-docs
          token: ${{ secrets.HELICONE_DOCS_PAT }}

      - name: Set up workspace
        run: |
          mkdir -p helicone-docs/docs/templates

      - name: Copy cookbooks to docs
        run: |
          cd helicone-templates
          for file in ${{ steps.changed_files.outputs.CHANGED_FILES }}; do
            template_name=$(echo $file | cut -d/ -f2)
            mkdir -p ../helicone-docs/docs/templates/$template_name
            cp $file ../helicone-docs/docs/templates/$template_name/index.md
            echo "Copied $file to docs/templates/$template_name/index.md"
          done

      - name: Create PR in helicone-docs
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.HELICONE_DOCS_PAT }}
          path: helicone-docs
          commit-message: "docs: sync template cookbooks from helicone-templates"
          title: "Sync template cookbooks from helicone-templates"
          body: |
            This PR synchronizes template cookbooks from the helicone-templates repository.

            Updated templates:
            ${{ steps.changed_files.outputs.CHANGED_FILES }}

            Automated PR from GitHub Actions workflow.
          branch: sync-template-cookbooks-${{ github.run_id }}
          delete-branch: true
