name: Test Templates

on:
  push:
    branches: [main]
    paths:
      - "templates/**"
      - ".github/workflows/test-templates.yml"
  pull_request:
    branches: [main]
    paths:
      - "templates/**"
      - ".github/workflows/test-templates.yml"

jobs:
  test-python-templates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [python-fastapi] # Add more templates here as they're created
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install pytest
        run: pip install pytest

      - name: Install template requirements
        run: |
          cd templates/${{ matrix.template }}/template
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd templates/${{ matrix.template }}/template
          python -m pytest -q

  # Add more jobs for other language templates as needed
  # test-node-templates:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       template: []  # e.g. node-express
  #   steps:
  #     # Node.js specific steps
